# Kotlin
kotlin.code.style=official
kotlin.mpp.stability.nowarn=true

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.java.installations.auto-download=true
org.gradle.java.home=C\:\\Program Files\\Java\\jdk-17

# Compose
compose.version=1.7.1
